# Site settings
title: IEEE Cluster Conference Series
email: balaji@anl.gov
description: > # this means to ignore newlines until "baseurl:"
  Webpage of the IEEE Cluster Conference Series
baseurl: ""
url: "https://clustercomp.org/committee/"

# Build settings
markdown: kramdown

highlighter: rouge
